@startuml Statics
class Légende{
    - private
    # protected
    + public
    {abstract} abstract
    {static} static
}
package entity{
    
    abstract class Entity #888888{
        + Entity(Point3D):Entity
        ==
        - id:String
        + getId():String
        --
        # position:Point3D
        + getPosition():Point3D
        --
        # collisionBox:CollisionBox
        + getCollisionBox():CollisionBox
        --
        # component:Component
        # {abstract} buildComponent():Component
        + getComponent():Component
        --
        # update(double):void
        # fall():void
        # correctCollisions():void
        --
        onMouseEntered(MouseEvent):void
        onMouseExit(MouseEvent):void
    }
    
    package entity.static{
        class StaticEntity{

        }
        StaticEntity --|> Entity
        interface EatableStatic{
            + onGetEaten(Herbivore):void
        }
        class TallGrass
        TallGrass --|> StaticEntity
        TallGrass --|> EatableStatic
        class FirTree{
            
        }
        FirTree --|> StaticEntity
        class Pine{
        }
        Pine --|> StaticEntity
        class Tipi{
        }
        Tipi --|> StaticEntity
        class AppleTree{
            - apples:Hashtable<String, Apple>
            - RandomizeApples(int):Hashtable<String, Apple>
            + getApples():Hashtable<String, Apple>

        }
        AppleTree --|> StaticEntity
    }
    package entity.item{
        
        abstract class Item{
            'function called whenever the Item is added to an inventory
            + {abstract}onAddToInventory(Human, Inventory):void
            'called when an Item is removed from an inventory.
            'used for things such as placing the Item in the world, etc.
            + {abstract}onRemoveFromInventory(Human, Inventory):void
        }
        Item --|> Entity
        class Apple
        Apple --|> Item
        Apple --> AppleTree
    }
    package entity.living{
        package entity.living.animal{
            abstract class Herbivore{
                + targetEatableStatic(EatableStatic):void
                + eat(EatableStatic):void
            }
            Herbivore -up-> EatableStatic
        }
    }
}
@enduml